# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e2b5b84c24b79e122f311e8d906e3dc25d887ea136d36b651e9745a1bf31841bd9771e2858a844f0ef53bbc704a1495759c656f485fd542278d7f499c36184

test:
  secret_key_base: 15904934ce40ae5b4665376391f958943433a912582ac2e54d3089f623b64a7d31a2dee86c529abe3a292ed31402002bd5d7ed5acfdb49316c362ffed49428ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
